version: '3'
services:
  app:
    image: koda/docker-knowledge
    ports:
      - 8080:8080
    volumes:
      - app_data:/root/.knowledge
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  app_data:
